web:
  file_home: file:/home/
  IP: localhost
#  IP: 182.247.245.27
  #  IP: 192.168.8.29
  #  IP: 192.168.8.19
  packaging: war
  tomcat_war: <exclusions><exclusion><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-tomcat</artifactId></exclusion></exclusions>

#spring
spring:
  profiles:
#      active: test
      active: production
#      active: develop
  freemarker:
    allow-request-override: false #页面热加载
    suffix: .html
    expose-spring-macro-helpers: false
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
  servlet:
    multipart:
      max-file-size: 2048
      max-request-size: 2048
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  thymeleaf:
    prefix: classpath:/templates/
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.file_home}


#  servlet:
#    context-path: /baiyajin

#logging日志
logging:
  level:
    com.baiyajin: DEBUG
  config: classpath:logback_spring.xml #实体扫描，多个package用逗号或者分号分隔


#mybatis plus 设置
mybatis-plus:
#  mapper-locations: classpath:mapper/*/*.xml
  mapper-locations: classpath:mapper/*/*.xml
  typeAliasesPackage: com.baiyajin.entity #实体扫描，多个package用逗号或者分号分隔
  global-config.refresh-mapper: true #刷新mapper 调试神器









